name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run test:e2e

  build:
    runs-on: ubuntu-latest

    needs: [e2e]

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY_NAME }}/${{ vars.REPOSITORY_NAME }}

      - name: Login to Cloud.ru Artifact Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_NAME }}
          username: ${{ secrets.CLOUD_RU_ID }}
          password: ${{ secrets.CLOUD_RU_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}